name: cicd

on:
  schedule:
    - cron: "0 21 * * 1"
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  bca87534df: # Escolhido arbitrariamente
    name: new_matches
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v5
        with:
          ref: main
          fetch-depth: 1
          persist-credentials: true
          
      - uses: astral-sh/setup-uv@v10
        with:
          enable-cache: true

      - name: install_packages
        run: uv sync --locked

      - name: fetch_matches
        env:
          "FETCH_ONLY": "1"
        run: uv run python ingestion/fetch_matches.py
    
      - name: check
        id: bka7798984es # Escolhido arbitrariamente
        run: |
          if [ -n "$(git status --porcelain datasets/raw)" ]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi
    
      - name: user
        if: steps.bka7798984es.outputs.changed == 'true'
        run: |
          git config user.name "rafaelnakayama"
          git config user.email "rafaelnakayama2003@gmail.com"
          git add datasets/raw
          git commit -m "chore: weekly fetch update"
          git push origin main